/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/bottom-sheet.vue')['default']
    Item: typeof import('./src/components/item.vue')['default']
    ItemForm: typeof import('./src/components/item-form.vue')['default']
  }
}
